name: bot-taks-scheduler
on:
  schedule:
    - cron: '0 1 * * *' #01 Hour UTC = 8 Hour GMT+7
    - cron: '0 6 * * *' #06 Hour UTC = 13 Hour GMT+7
    - cron: '0 12 * * *' #06 Hour UTC = 19 Hour GMT+7
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v2.3.4
      - name: Setup Python Environment
        uses: actions/setup-python@v2.2.2
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create wiki folder
        run: mkdir wiki
      - name: Use 1.1.1.1 DNS
        run: echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Scrape data from หมอพร้อม dashboard using selenium
        working-directory: vaccine
        run: python scrape-moh-prompt.py
      - name: Upload json to wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
          source-directory: './wiki'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
